In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/GFG_data.csv')

In [ ]:
df

         Name  ID  Gender  Salary
0     Utkarsh   1    Male   95000
1      Kartik   2    Male   85000
2   Aishwarya   3  Female   75000
3       Anand   4    Male   65000
4     Shalini   5  Female   90000
5      Pratik   6    Male   80000
6    Monalika   7  Female   70000
7      Ayesha   8  Female   60000
8       Anant   9    Male  100000
9   Shamiksha  10  Female   45000
10   Prashant  11    Male   55000
11     Mohini  12  Female   65000

In [ ]:
df.head()

        Name  ID  Gender  Salary
0    Utkarsh   1    Male   95000
1     Kartik   2    Male   85000
2  Aishwarya   3  Female   75000
3      Anand   4    Male   65000
4    Shalini   5  Female   90000

In [ ]:
df.tail()

         Name  ID  Gender  Salary
7      Ayesha   8  Female   60000
8       Anant   9    Male  100000
9   Shamiksha  10  Female   45000
10   Prashant  11    Male   55000
11     Mohini  12  Female   65000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    12 non-null     object
 1   ID      12 non-null     int64
 2   Gender  12 non-null     object
 3   Salary  12 non-null     int64
dtypes: int64(2), object(2)
memory usage: 516.0+ bytes

In [ ]:
df.isna()

     Name     ID  Gender  Salary
0   False  False   False   False
1   False  False   False   False
2   False  False   False   False
3   False  False   False   False
4   False  False   False   False
5   False  False   False   False
6   False  False   False   False
7   False  False   False   False
8   False  False   False   False
9   False  False   False   False
10  False  False   False   False
11  False  False   False   False

In [ ]:
df.isna().sum()

Name      0
ID        0
Gender    0
Salary    0
dtype: int64

In [ ]:
df.isnull().sum()

Name      0
ID        0
Gender    0
Salary    0
dtype: int64

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

### Accessing Coloumns and Rows

In [ ]:
df

         Name  ID  Gender  Salary
0     Utkarsh   1    Male   95000
1      Kartik   2    Male   85000
2   Aishwarya   3  Female   75000
3       Anand   4    Male   65000
4     Shalini   5  Female   90000
5      Pratik   6    Male   80000
6    Monalika   7  Female   70000
7      Ayesha   8  Female   60000
8       Anant   9    Male  100000
9   Shamiksha  10  Female   45000
10   Prashant  11    Male   55000
11     Mohini  12  Female   65000

In [ ]:
df['Salary']

0      95000
1      85000
2      75000
3      65000
4      90000
5      80000
6      70000
7      60000
8     100000
9      45000
10     55000
11     65000
Name: Salary, dtype: int64

In [ ]:
df.Salary

0      95000
1      85000
2      75000
3      65000
4      90000
5      80000
6      70000
7      60000
8     100000
9      45000
10     55000
11     65000
Name: Salary, dtype: int64

In [ ]:
df[['Name','Salary']]

         Name  Salary
0     Utkarsh   95000
1      Kartik   85000
2   Aishwarya   75000
3       Anand   65000
4     Shalini   90000
5      Pratik   80000
6    Monalika   70000
7      Ayesha   60000
8       Anant  100000
9   Shamiksha   45000
10   Prashant   55000
11     Mohini   65000

In [ ]:
df[['ID','Salary','Gender']]

    ID  Salary  Gender
0    1   95000    Male
1    2   85000    Male
2    3   75000  Female
3    4   65000    Male
4    5   90000  Female
5    6   80000    Male
6    7   70000  Female
7    8   60000  Female
8    9  100000    Male
9   10   45000  Female
10  11   55000    Male
11  12   65000  Female

In [ ]:
df['Salary'>48000]

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
df['Salary']>48000

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9     False
10     True
11     True
Name: Salary, dtype: bool

In [ ]:
(df['Salary']>48000).sum()  #Not a desired output

np.int64(11)

In [ ]:
df[df['Salary']>88000]

      Name  ID  Gender  Salary
0  Utkarsh   1    Male   95000
4  Shalini   5  Female   90000
8    Anant   9    Male  100000

In [ ]:
df[(df['Salary']>60000) & (df['Gender']=='Female')]

         Name  ID  Gender  Salary
2   Aishwarya   3  Female   75000
4     Shalini   5  Female   90000
6    Monalika   7  Female   70000
11     Mohini  12  Female   65000

In [ ]:
df[(df['ID']<5) & (df['ID']>10)]

Empty DataFrame
Columns: [Name, ID, Gender, Salary]
Index: []

In [ ]:
df[(df['ID']<5) | (df['ID']>10)]  #Select OR operator for multiple selection in the same coloumn

         Name  ID  Gender  Salary
0     Utkarsh   1    Male   95000
1      Kartik   2    Male   85000
2   Aishwarya   3  Female   75000
3       Anand   4    Male   65000
10   Prashant  11    Male   55000
11     Mohini  12  Female   65000

In [ ]:
# Accessing a Row

df.index()

TypeError: 'RangeIndex' object is not callable

In [ ]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [ ]:
#Assigning the Number to the index

df.index = range(201,213)

In [ ]:
df

          Name  ID  Gender  Salary
201    Utkarsh   1    Male   95000
202     Kartik   2    Male   85000
203  Aishwarya   3  Female   75000
204      Anand   4    Male   65000
205    Shalini   5  Female   90000
206     Pratik   6    Male   80000
207   Monalika   7  Female   70000
208     Ayesha   8  Female   60000
209      Anant   9    Male  100000
210  Shamiksha  10  Female   45000
211   Prashant  11    Male   55000
212     Mohini  12  Female   65000

In [ ]:
# 2 Ways to Access any Row

df.loc[210]

Name      Shamiksha
ID               10
Gender       Female
Salary        45000
Name: 210, dtype: object

In [ ]:
df.iloc[9]

Name      Shamiksha
ID               10
Gender       Female
Salary        45000
Name: 210, dtype: object

In [ ]:
df.iloc[12]

IndexError: single positional indexer is out-of-bounds

In [ ]:
df.iloc[12]= ['Manthan',21,'Male',215000]

IndexError: iloc cannot enlarge its target object

In [ ]:
df.loc[217]= ['Manthan',21,'Male',215000]

In [ ]:
df

          Name  ID  Gender  Salary
201    Utkarsh   1    Male   95000
202     Kartik   2    Male   85000
203  Aishwarya   3  Female   75000
204      Anand   4    Male   65000
205    Shalini   5  Female   90000
206     Pratik   6    Male   80000
207   Monalika   7  Female   70000
208     Ayesha   8  Female   60000
209      Anant   9    Male  100000
210  Shamiksha  10  Female   45000
211   Prashant  11    Male   55000
212     Mohini  12  Female   65000
12     Manthan  21    Male  215000
217    Manthan  21    Male  215000

In [ ]:
df.iloc[10]

Name      Prashant
ID              11
Gender        Male
Salary       55000
Name: 211, dtype: object

In [ ]:
df.iloc[1,8,10]

IndexingError: Too many indexers

In [ ]:
df.iloc[[1,8,10]]

         Name  ID Gender  Salary
202    Kartik   2   Male   85000
209     Anant   9   Male  100000
211  Prashant  11   Male   55000

In [ ]:
df.iloc[1:8]

          Name  ID  Gender  Salary
202     Kartik   2    Male   85000
203  Aishwarya   3  Female   75000
204      Anand   4    Male   65000
205    Shalini   5  Female   90000
206     Pratik   6    Male   80000
207   Monalika   7  Female   70000
208     Ayesha   8  Female   60000

In [ ]:
df.iloc[1:8][['Name','Salary']]

          Name  Salary
202     Kartik   85000
203  Aishwarya   75000
204      Anand   65000
205    Shalini   90000
206     Pratik   80000
207   Monalika   70000
208     Ayesha   60000

In [ ]:
df.loc[201:209][['ID','Gender']]

     ID  Gender
201   1    Male
202   2    Male
203   3  Female
204   4    Male
205   5  Female
206   6    Male
207   7  Female
208   8  Female
209   9    Male

In [ ]:
# Creating a new Coloumn

df['Updated_Salary'] = df['Salary']*1.35

In [ ]:
df

          Name  ID  Gender  Salary  Updated_Salary
201    Utkarsh   1    Male   95000        128250.0
202     Kartik   2    Male   85000        114750.0
203  Aishwarya   3  Female   75000        101250.0
204      Anand   4    Male   65000         87750.0
205    Shalini   5  Female   90000        121500.0
206     Pratik   6    Male   80000        108000.0
207   Monalika   7  Female   70000         94500.0
208     Ayesha   8  Female   60000         81000.0
209      Anant   9    Male  100000        135000.0
210  Shamiksha  10  Female   45000         60750.0
211   Prashant  11    Male   55000         74250.0
212     Mohini  12  Female   65000         87750.0
12     Manthan  21    Male  215000        290250.0
217    Manthan  21    Male  215000        290250.0

In [ ]:
df['Updated_Salary'] = df['Salary']*df['ID']

In [ ]:
df

          Name  ID  Gender  Salary  Updated_Salary
201    Utkarsh   1    Male   95000           95000
202     Kartik   2    Male   85000          170000
203  Aishwarya   3  Female   75000          225000
204      Anand   4    Male   65000          260000
205    Shalini   5  Female   90000          450000
206     Pratik   6    Male   80000          480000
207   Monalika   7  Female   70000          490000
208     Ayesha   8  Female   60000          480000
209      Anant   9    Male  100000          900000
210  Shamiksha  10  Female   45000          450000
211   Prashant  11    Male   55000          605000
212     Mohini  12  Female   65000          780000
12     Manthan  21    Male  215000         4515000
217    Manthan  21    Male  215000         4515000

In [ ]:
# Dropping a Row and Coloumn

df.drop('Updated_Salary', axis = 1)

          Name  ID  Gender  Salary
201    Utkarsh   1    Male   95000
202     Kartik   2    Male   85000
203  Aishwarya   3  Female   75000
204      Anand   4    Male   65000
205    Shalini   5  Female   90000
206     Pratik   6    Male   80000
207   Monalika   7  Female   70000
208     Ayesha   8  Female   60000
209      Anant   9    Male  100000
210  Shamiksha  10  Female   45000
211   Prashant  11    Male   55000
212     Mohini  12  Female   65000
12     Manthan  21    Male  215000
217    Manthan  21    Male  215000

In [ ]:
df.drop('Updated_Salary', axis = 1, inplace = True)        # Permanent deletion

In [ ]:
df

          Name  ID  Gender  Salary
201    Utkarsh   1    Male   95000
202     Kartik   2    Male   85000
203  Aishwarya   3  Female   75000
204      Anand   4    Male   65000
205    Shalini   5  Female   90000
206     Pratik   6    Male   80000
207   Monalika   7  Female   70000
208     Ayesha   8  Female   60000
209      Anant   9    Male  100000
210  Shamiksha  10  Female   45000
211   Prashant  11    Male   55000
212     Mohini  12  Female   65000
12     Manthan  21    Male  215000
217    Manthan  21    Male  215000

In [ ]:
df.sort_index(ascending = False)

          Name  ID  Gender  Salary
217    Manthan  21    Male  215000
212     Mohini  12  Female   65000
211   Prashant  11    Male   55000
210  Shamiksha  10  Female   45000
209      Anant   9    Male  100000
208     Ayesha   8  Female   60000
207   Monalika   7  Female   70000
206     Pratik   6    Male   80000
205    Shalini   5  Female   90000
204      Anand   4    Male   65000
203  Aishwarya   3  Female   75000
202     Kartik   2    Male   85000
201    Utkarsh   1    Male   95000
12     Manthan  21    Male  215000

In [ ]:
df.sort_values(by = 'Salary', ascending = False)

          Name  ID  Gender  Salary
217    Manthan  21    Male  215000
12     Manthan  21    Male  215000
209      Anant   9    Male  100000
201    Utkarsh   1    Male   95000
205    Shalini   5  Female   90000
202     Kartik   2    Male   85000
206     Pratik   6    Male   80000
203  Aishwarya   3  Female   75000
207   Monalika   7  Female   70000
204      Anand   4    Male   65000
212     Mohini  12  Female   65000
208     Ayesha   8  Female   60000
211   Prashant  11    Male   55000
210  Shamiksha  10  Female   45000

In [ ]:
df['Age'] = [23,22,23,45,45,60,58,55,41,29,32,19,22,34]

In [ ]:
df

          Name  ID  Gender  Salary  Age
201    Utkarsh   1    Male   95000   23
202     Kartik   2    Male   85000   22
203  Aishwarya   3  Female   75000   23
204      Anand   4    Male   65000   45
205    Shalini   5  Female   90000   45
206     Pratik   6    Male   80000   60
207   Monalika   7  Female   70000   58
208     Ayesha   8  Female   60000   55
209      Anant   9    Male  100000   41
210  Shamiksha  10  Female   45000   29
211   Prashant  11    Male   55000   32
212     Mohini  12  Female   65000   19
12     Manthan  21    Male  215000   22
217    Manthan  21    Male  215000   34

In [ ]:
df.sort_values(by = ['Salary','Age'], ascending = False)

          Name  ID  Gender  Salary  Age
217    Manthan  21    Male  215000   34
12     Manthan  21    Male  215000   22
209      Anant   9    Male  100000   41
201    Utkarsh   1    Male   95000   23
205    Shalini   5  Female   90000   45
202     Kartik   2    Male   85000   22
206     Pratik   6    Male   80000   60
203  Aishwarya   3  Female   75000   23
207   Monalika   7  Female   70000   58
204      Anand   4    Male   65000   45
212     Mohini  12  Female   65000   19
208     Ayesha   8  Female   60000   55
211   Prashant  11    Male   55000   32
210  Shamiksha  10  Female   45000   29

In [ ]:
df.sort_values(by = ['Age','Salary'], ascending = False)

          Name  ID  Gender  Salary  Age
206     Pratik   6    Male   80000   60
207   Monalika   7  Female   70000   58
208     Ayesha   8  Female   60000   55
205    Shalini   5  Female   90000   45
204      Anand   4    Male   65000   45
209      Anant   9    Male  100000   41
217    Manthan  21    Male  215000   34
211   Prashant  11    Male   55000   32
210  Shamiksha  10  Female   45000   29
201    Utkarsh   1    Male   95000   23
203  Aishwarya   3  Female   75000   23
12     Manthan  21    Male  215000   22
202     Kartik   2    Male   85000   22
212     Mohini  12  Female   65000   19

In [ ]:
df.sort_values(by = ['Gender','Salary'], ascending = True)

          Name  ID  Gender  Salary  Age
210  Shamiksha  10  Female   45000   29
208     Ayesha   8  Female   60000   55
212     Mohini  12  Female   65000   19
207   Monalika   7  Female   70000   58
203  Aishwarya   3  Female   75000   23
205    Shalini   5  Female   90000   45
211   Prashant  11    Male   55000   32
204      Anand   4    Male   65000   45
206     Pratik   6    Male   80000   60
202     Kartik   2    Male   85000   22
201    Utkarsh   1    Male   95000   23
209      Anant   9    Male  100000   41
12     Manthan  21    Male  215000   22
217    Manthan  21    Male  215000   34